#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export INVDES_ROOT="${INVDES_ROOT:-$(cd "${SCRIPT_DIR}/.." && pwd)}"
export PROJECT_ROOT="${INVDES_ROOT}/00_project"
export CODE_ROOT="${INVDES_ROOT}/01_code"
export INV_DES_FLOW_ROOT="${CODE_ROOT}/InvDesFlow"
export PHONONBENCH_ROOT="${CODE_ROOT}/PhononBench"
export MATTERSIM_ROOT="${CODE_ROOT}/MatterSim"
export ENVS_ROOT="${INVDES_ROOT}/02_envs"
export DATASETS_ROOT="${INVDES_ROOT}/03_datasets"
export MODELS_ROOT="${INVDES_ROOT}/04_models"
export STEPS_ROOT="${INVDES_ROOT}/05_steps"
export RUNS_ROOT="${INVDES_ROOT}/06_runs"
export LOGS_ROOT="${INVDES_ROOT}/07_logs"
export LOGS_BY_RUN_ROOT="${LOGS_ROOT}/09_runs_by_name"
export ARCHIVE_ROOT="${INVDES_ROOT}/08_archive"

export SOURCE_CIF_DIR="${DATASETS_ROOT}/01_source_cif/high_quality_280"
export SOURCE_CIF_REFERENCE_ROOT="${DATASETS_ROOT}/01_source_cif"
export DIFFCSP_DATASET_DIR="${DATASETS_ROOT}/02_diffcsp_dataset/mobility2d_highquality280"
export ALIGNN_MOBILITY_DATA_DIR="${DATASETS_ROOT}/03_alignn_mobility_dataset/mobility_reg_v1"
export METADATA_DIR="${DATASETS_ROOT}/04_metadata"

export DIFFCSP_ROOT="${INV_DES_FLOW_ROOT}/DiffCSP"
export ALIGNN_CODE_ROOT="${INV_DES_FLOW_ROOT}/alignn"
export MEGNET_PREDICT_SCRIPT="${INV_DES_FLOW_ROOT}/pred_formation_energy.py"
export DIFFCSP_DATASET_NAME="mobility2d_highquality280"
export DIFFCSP_EXPNAME="mobility2d_highquality280_ft_v1"

export DIFFCSP_PRETRAINED_DIR="${MODELS_ROOT}/01_diffcsp_generator/pretrained"
export DIFFCSP_PRETRAINED_CKPT="${DIFFCSP_PRETRAINED_DIR}/PretrainGenerationModel.ckpt"
export DIFFCSP_FINETUNED_DIR="${MODELS_ROOT}/01_diffcsp_generator/finetuned/mobility2d_highquality280_ft_v1"
export DIFFCSP_FINETUNED_CKPT="${DIFFCSP_FINETUNED_DIR}/best.ckpt"

export ALIGNN_BANDGAP_MODEL_DIR="${MODELS_ROOT}/02_alignn_bandgap_nonmetal"
export ALIGNN_BANDGAP_CONFIG="${ALIGNN_BANDGAP_MODEL_DIR}/config.json"
export ALIGNN_BANDGAP_CKPT="${ALIGNN_BANDGAP_MODEL_DIR}/last_model.pt"

export MEGNET_MODEL_DIR="${MODELS_ROOT}/03_megnet_formation_energy"
export MEGNET_MODEL_PATH="${MEGNET_MODEL_DIR}/FormEGNN-weight.hdf5"
export MEGNET_MODEL_CONFIG_PATH="${MEGNET_MODEL_DIR}/megnet_formation_energy.hdf5.json"

export ALIGNN_MOBILITY_MODEL_DIR="${MODELS_ROOT}/04_alignn_mobility/mobility_reg_v1_bs8_lr5e4_wu200_nw4"
export ALIGNN_MOBILITY_MODEL_CONFIG="${ALIGNN_MOBILITY_MODEL_DIR}/config.json"
export ALIGNN_MOBILITY_MODEL_CKPT="${ALIGNN_MOBILITY_MODEL_DIR}/best_model.pt"

export CURRENT_FULL_PIPELINE_LINK="${RUNS_ROOT}/current__latest_default_semiconductor_pipeline"
export DEFAULT_GENERATION_RUN_ID="20260408__generated_1000_structures__from_mobility2d_highquality280_ft_v1"
export DEFAULT_GENERATION_RUN_LABEL="20260408_generated_1000_structures"
export DEFAULT_GENERATION_PT_DIR="${RUNS_ROOT}/${DEFAULT_GENERATION_RUN_ID}/03_generate_structures/generated_pt"
export DEFAULT_GENERATION_CIF_DIR="${RUNS_ROOT}/${DEFAULT_GENERATION_RUN_ID}/03_generate_structures/generated_cif"

export STEP01_DIR="${STEPS_ROOT}/01_build_dataset"
export STEP02_DIR="${STEPS_ROOT}/02_finetune_generator"
export STEP03_DIR="${STEPS_ROOT}/03_generate_structures"
export STEP04_DIR="${STEPS_ROOT}/04_alignn_bandgap_nonmetal"
export STEP05_DIR="${STEPS_ROOT}/05_megnet_formation_energy"
export STEP05B_DIR="${STEPS_ROOT}/05b_phononbench_stability"
export STEP06_DIR="${STEPS_ROOT}/06_alignn_mobility_rank"
export STEP07_DIR="${STEPS_ROOT}/07_export_top10_cif"
export STEP08_DIR="${STEPS_ROOT}/08_orchestration"
